name: Tests and Coverage

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src && pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        make ci-test
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./src/coverage.xml
        fail_ci_if_error: false
        verbose: true
        
    - name: Upload test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: pytest-results
        path: ./src/test-results.xml
        reporter: java-junit
        fail-on-error: true